FORMAT: 1A
HOST: http://www.google.com

# stein
`stein` is a TAP consumer. Supported TAP-based protocols include: TAP, TAP13, TAP-Y, TAP-J.

# Group Projects
A project groups test results.

## Projects Collection [/projects]
### List all Projects [GET]
+ Response 200 (application/json)

        ["project1", "project2"]

### Create Project [PUT]
+ Response 200 (application/json)

        "created"

## Tests within a project [/projects/{project}/tests]
### Get test results [GET]
+ Response 200 (application/json)

        ["2014-03-04T15:06:03Z"]

+ Parameters
    + project (required, string, `"project1"`) ... Name of the project to get test results for.

## Tests [/projects/{project}/tests/{id}]

### Retrieve a test result [GET]
+ Response 200 (application/json)

    + Body

            { "Type": "suite", "Final": {"Total": 10, "Pass": 8, "Fail": 1, "Error": 1}, "Time": "5.03" }

+ Parameters
    + project (required, string, `"project1"`) ... Name of the project to get test results for.
    + id (required, string, `"2014-03-04T15:06:03Z"`) ... ID (timestamp) of the created test.